use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

target 'BiliBili' do
#    pod 'Moya'
    pod 'Moya/RxSwift', '~> 11.0'
    
    pod 'RxDataSources', '~> 3'

# State
#    pod 'ReSwift'
  # UI Component
  
  ## Rich text
#  pod 'YYText'

  ## QRcode
#  pod 'EFQRCode'
  ## Banner
#  pod 'SDCycleScrollView'

  ## Alert
  pod 'Toaster', '~> 2.1.0'
  
  ## Keyboard
  pod 'IQKeyboardManagerSwift'
  
  ## Theme
  pod 'SwiftTheme', '~> 0.3.3'

  ## Form
#  pod 'Eureka'

  ## Picker
#  pod 'ActionSheetPicker-3.0'
#  pod 'McPicker'

  ## Menu
  
  #Others
  
  pod 'CryptoSwift'

  ## Parser
  pod 'ObjectMapper'
  
  ## Responsive
#  pod 'RxSwift'

  ## Layout
  pod 'SnapKit'
  
  ## Refresh
#  pod 'MJRefresh'

  ## Image download
  pod 'Kingfisher', '~> 4.6.3'

  ## Database
  pod 'RealmSwift'

end
