use_frameworks!
platform :ios, '10.0'

target 'BiliBili' do
	pod 'Moya'
  
  # UI Component
  
  ## Rich text
  pod 'YYText'
  
  ## QRcode
#  pod 'EFQRCode'
  ## Banner
  pod 'SDCycleScrollView'
  
  ## Alert
  pod 'SVProgressHUD'
  
  ## Keyboard
  pod 'IQKeyboardManagerSwift'
  
  ## Form
  pod 'Eureka'
  
  ## Picker
  pod 'ActionSheetPicker-3.0'
#  pod 'McPicker'

  ## Menu
  pod 'XLPagerTabStrip', '~> 8.0'
  #Others
  
  pod 'CryptoSwift'

  ## Parser
  pod 'ObjectMapper'
  # Pods for MemberCenterIOS
  
  ## Call back
  pod 'PromiseKit'
  
  ## Layout
  pod 'SnapKit'
  
  ## Refresh
  pod 'MJRefresh'
  
  ## Image download
  pod 'Kingfisher'

end
